/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLinks: typeof import('./src/components/AppLinks.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    HomeTop: typeof import('./src/components/HomeTop/HomeTop.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    TaskList: typeof import('./src/components/TaskList/TaskList.vue')['default']
    TestHttp: typeof import('./src/components/TestHttp.vue')['default']
    UBadge: typeof import('uview-pro/components/u-badge/u-badge.vue')['default']
    UButton: typeof import('uview-pro/components/u-button/u-button.vue')['default']
    UGap: typeof import('uview-pro/components/u-gap/u-gap.vue')['default']
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    UInput: typeof import('uview-pro/components/u-input/u-input.vue')['default']
    UNavbar: typeof import('uview-pro/components/u-navbar/u-navbar.vue')['default']
    UTabbar: typeof import('uview-pro/components/u-tabbar/u-tabbar.vue')['default']
  }
}
