/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/tabs/home" |
  "/pages/admin/create" |
  "/pages/admin/share" |
  "/pages/tabs/data" |
  "/pages/tabs/employee" |
  "/pages/tabs/msg" |
  "/pages/tabs/review" |
  "/pages/tabs/task" |
  "/pages/user/submit";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/tabs/task" | "/pages/tabs/review" | "/pages/tabs/data" | "/pages/tabs/employee" | "/pages/tabs/home" | "/pages/tabs/msg"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
